### ISSUE TITLE
maze incorrectly generated

### ISSUE THREAD

**Issue by wiekern** [Katee/maze#2]
as u mentioned, there is a bug which u could not reproduce. I thought I found it out. 

change this piece of code like following where i commented.
```
this.generateMaze = function () {
			// this.c = this.getCell(rand.randomInt(this.width), rand.randomInt(this.height));
			this.c = this.getCell(8,9);
			this.c.visited = true;
			this.mazeDo();
			while (this.stack.length !== 0) {
				 if (this.isDeadEnd(this.c.x, this.c.y) || this.isEnd(this.c.x, this.c.y) || this.isStart(this.c.x, this.c.y)) {
				//if (this.isDeadEnd(this.c.x, this.c.y)) { //this can fix this bug
					this.nextC = this.stack.pop();
					this.c = this.nextC;
				} else {
					this.mazeDo();
				}
			}
```
then u will reproduce this bug soon.

**Comment by Katee** [comment]
Hi @wiekern. Using your code for the `generateMaze` function did not generate a maze without any walls removed (I tried all combinations of the original lines vs. the ones you commented out). Could you be more specific about how you replicated the issue?

**Comment by wiekern** [comment]
forgot to say, the size of maze plays an important role. if u generated a 10x10 maze, then u could use my code 
```
this.c = this.getCell(8,9);
```
or if u don't want specify two certain numbers, please using
```
 this.c = this.getCell(this.width - 2, this.height-1);
```
Finally, u could generate a incorrect maze like
![image](https://user-images.githubusercontent.com/3865455/29184691-53da02d4-7e07-11e7-9fc8-692f80874875.png)

**Comment by Katee** [comment]
Using the line `this.c = this.getCell(this.width - 1, this.height);` causes an out of bounds issue.

Using the line `this.c = this.getCell(this.width - 1, this.height - 1);` does not replicate the issue.

Are you sure you don't have any other modifications to the code? Maybe you could post the exact code you have the replicates the issue as a gist and link to it here.

**Comment by wiekern** [comment]
sorry, it should be
```
this.c = this.getCell(this.width - 2, this.height-1);
```
I have pulled your code from github again, generated a maze after refreshing the page as 
![image](https://user-images.githubusercontent.com/3865455/29185994-658f1f6a-7e0b-11e7-97b3-979b183b4858.png)

**Comment by Katee** [comment]
Thanks @wiekern. This has been fixed and merged to master in https://github.com/Katee/maze/pull/3

**Comment by wiekern** [comment]
My pleasure, your project is awesome.
